version: '3.8'
services:
  greencheap_web:
    image: webdevops/php-apache:7.4
    container_name: greencheap_web
    ports:
      - 8042:80
      - 8043:443
    volumes:
      - ./:/app/
    networks: 
      - greencheap_net
  greencheap_mysql:
    image: mysql:8.0
    container_name: greencheap_mysql
    ports:
      - 3310:3306
    restart: always
    volumes:
      - ./tmp/docker_volume/greencheap/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: greencheappassword
    networks: 
      - greencheap_net
networks:
  greencheap_net:
    driver: bridge