version: '3.8'

services:
  postgres:
    image: 'postgres:alpine'
    ports:
      - 5432:5432
    volumes: 
      - gcdb:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=postgres
volumes: 
  gcdb: