version: "3.9"

services:
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: greencheap
            POSTGRES_DB: greencheap
    greencheap:
        image: greencheap/greencheap
        depends_on:
            - postgres
        ports:
            - 8000:80
        restart: always
        volumes:
            - ./:/var/www/html
    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
